version: '2'
services:
  web:
    restart: always
    build: ./web
    ports:
      - 80
    volumes:
      - ./log:/log
      - ./tmp:/tmp
  lb:
    image: dockercloud/haproxy
    links:
     - web
    ports:
     - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
